version: "3.3"
services:
  influxdb:
    image: influxdb
    restart: always
    network_mode: "bridge"
    volumes:
      - /share/ContainerData/influxdb/influxdb:/var/lib/influxdb
      - /share/ContainerData/influxdb/influxdb.conf:/var/lib/influxdb.conf
    ports:
      - "8086:8086"
    environment:
      TZ: "Europe/Warsaw"
  telegraf:
    image: telegraf
    restart: always
    network_mode: "bridge"
    volumes:
      - /share/ContainerData/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
